---
apiVersion: batch/v1
kind: Job
metadata:
  name: delay-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: delay
        image: alpine
        command: ["sh", "-c", "sleep 60"]
      restartPolicy: Never
  backoffLimit: 0
