{{- range .Values.global.products.postgres }}
{{- $sizeConfig := include "cpi-postgresql.getSizeConfig" (dict "Values" $.Values "tshirtSize" .tshirtSize) | fromYaml }}
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "{{ .name }}"
  namespace: "customer-{{ $.Values.global.customer.name }}"
  labels:
    team: acid
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  teamId: "acid"
  postgresql:
    version: "15"
    parameters:
      password_encryption: scram-sha-256
      max_connections: "800"
  numberOfInstances: 3
  volume:
    size: "{{ $sizeConfig.storage }}"
  users:
    delta: []
    edge: []
    edge_urid: []
  databases:
    deltadb: delta
    edgedb: edge
    edge_urid_db: edge_urid
  # Enable MetalLB/loadbalancer access to each deployment
  enableMasterLoadBalancer: true
  allowedSourceRanges:
    # IP ranges to access your cluster go here
    # We allow all traffic from within FDI by default
    - 10.24.0.0/16
    - 10.42.0.0/16
  resources:
    requests:
      cpu: "{{ $sizeConfig.cpuRequest }}"
      memory: "{{ $sizeConfig.memoryRequest }}"
    limits:
      cpu: "{{ $sizeConfig.cpuLimit }}"
      memory: "{{ $sizeConfig.memoryLimit }}"
---
{{- end }}
