{{- range .Values.global.products.postgres }}
{{- $sizeConfig := include "cpi-postgresql.getSizeConfig" (dict "Values" $.Values "tshirtSize" .tshirtSize) | fromYaml }}
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "{{ .name }}"
  namespace: "customer-{{ $.Values.global.customer.name }}"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
    parameters:
      password_encryption: scram-sha-256
  numberOfInstances: 3
  volume:
    size: "{{ $sizeConfig.storage }}"
  users:
    delta: []
    edge: []
  databases:
    deltadb: delta
    edgedb: edge
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: "{{ $sizeConfig.cpuRequest }}"
      memory: "{{ $sizeConfig.memoryRequest }}"
    limits:
      cpu: "{{ $sizeConfig.cpuLimit }}"
      memory: "{{ $sizeConfig.memoryLimit }}"
---
{{- end }}